Repository osmlab/atlas-generator, pull requests merged in 2018-06, with the labels that each got.

#37 DNM: Parametrize force-country-slicing
  dependencies.gradle
  src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
  src/main/java/org/openstreetmap/atlas/generator/world/WorldAtlasGenerator.java
Labels: Data Change, New Feature

#38 Fixed bug with pbf sharding initialization
  src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
Labels: Bug

#39 Logger level cleanup for AtlasGeneratorHelper
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
Labels: Enhancement
