Repository osmlab/atlas-generator, pull requests merged in 2018-10, with the labels that each got.

#54 Switched caching to use HadoopAtlasFileCache instead of custom code
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
Labels: Enhancement

#56 Protect AtlasGenerator from failing statistics
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
Labels: Bug, Enhancement

#57 Travis - Use trusty and sudo false
  .travis.yml
Labels: Bug

#55 Added a default boundary map and configuration options to WorldAtlasGenerator
  src/integrationTest/java/org/openstreetmap/atlas/generator/world/WorldAtlasGeneratorIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/generator/world/WorldAtlasGenerator.java
Labels: Enhancement

#58 Using Spark Broadcast variables
  src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
Labels: Enhancement

#59 DNM: AtlasGenerator cleanup and fix AtlasScheme being dropped
  config/checkstyle/checkstyle.xml
  dependencies.gradle
  src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorParameters.java
  src/main/java/org/openstreetmap/atlas/generator/tools/caching/HadoopAtlasFileCache.java
  src/main/java/org/openstreetmap/atlas/generator/tools/streaming/ResourceFileSystem.java
  src/main/java/org/openstreetmap/atlas/generator/tools/streaming/SeekableResourceStream.java
  src/main/java/org/openstreetmap/atlas/generator/world/WorldAtlasGenerator.java
  src/test/java/org/openstreetmap/atlas/generator/tools/caching/HadoopAtlasFileCacheTest.java
Labels: Bug, Enhancement

#60 Updates to HadoopAtlasFileCache
  src/main/java/org/openstreetmap/atlas/generator/tools/caching/HadoopAtlasFileCache.java
  src/main/java/org/openstreetmap/atlas/generator/tools/filesystem/FileSystemHelper.java
  src/test/java/org/openstreetmap/atlas/generator/tools/caching/HadoopAtlasFileCacheTest.java
Labels: Enhancement

#61 Added gradle run option
  README.md
  build.gradle
  config/images/josm-atlas1.png
  config/images/josm-atlas2.png
  gradle.properties
  gradle/execution.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: New Feature
