Repository osmlab/atlas-generator, pull requests merged in 2019-03, with the labels that each got.

#83 Jdk11 compatibility
  .travis.yml
  gradle/quality.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: Bug, Enhancement

#84 Upgrade to Gradle 5
  README.md
  build.gradle
  config/checkstyle/checkstyle.xml
  dependencies.gradle
  gradle/execution.gradle
  gradle/quality.gradle
  src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorParameters.java
  src/main/java/org/openstreetmap/atlas/generator/creator/RawAtlasCreator.java
Labels: Enhancement

#85 Update links and gradle 5
  gradle/execution.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: Enhancement

#86 Streamline AtlasGenerator and improve slicing performance
  dependencies.gradle
  src/integrationTest/java/org/openstreetmap/atlas/generator/AtlasGeneratorIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/generator/slicing/DynamicRelationSlicingIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorJobGroup.java
Labels: Enhancement

#89 Dump ResourceFileSystem to disk
  src/main/java/org/openstreetmap/atlas/generator/tools/streaming/ResourceFileSystem.java
  src/test/java/org/openstreetmap/atlas/generator/tools/streaming/resource/ResourceFileSystemTest.java
Labels: New Feature

#90 Update Missing Shard Verifier to use configurable way filter
  src/main/java/org/openstreetmap/atlas/generator/sharding/AtlasMissingShardVerifier.java
Labels: Enhancement
