Repository osmlab/atlas-generator, pull requests merged in 2019-04, with the labels that each got.

#88 Added in configuration option for filtered output
  src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorJobGroup.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorParameters.java
Labels: Enhancement

#91 Fixed RawAtlasCountrySlicer constructors, added edge-only subatlas caching
  dependencies.gradle
  src/integrationTest/java/org/openstreetmap/atlas/generator/slicing/DynamicRelationSlicingIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorJobGroup.java
  src/main/java/org/openstreetmap/atlas/generator/creator/RawAtlasCreator.java
  src/main/java/org/openstreetmap/atlas/generator/world/WorldAtlasGenerator.java
Labels: Enhancement

#87 Run integration tests for PR builds as well
  .travis/build.sh
Labels: Enhancement

#94 Make ResourceFileSystem clearable
  .travis/sonar.sh
  src/main/java/org/openstreetmap/atlas/generator/tools/streaming/ResourceFileSystem.java
Labels: Enhancement

#93 Simplification and cleanup of SparkJob
  src/integrationTest/java/org/openstreetmap/atlas/generator/tools/spark/SparkJobIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/generator/tools/spark/SparkJob.java
Labels: Breaking Change, Enhancement

#95 Fixed wrong RDD pair map for relation slicing
  src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
Labels: Bug

#96 Pbf Verifier
  dependencies.gradle
  src/main/java/org/openstreetmap/atlas/generator/sharding/PbfFilePathFilter.java
  src/main/java/org/openstreetmap/atlas/generator/sharding/PbfVerifier.java
  src/test/java/org/openstreetmap/atlas/generator/sharding/PbfVerifierTest.java
  src/test/resources/org/openstreetmap/atlas/generator/sharding/10-313-380.pbf
  src/test/resources/org/openstreetmap/atlas/generator/sharding/10-313-381.pbf
  src/test/resources/org/openstreetmap/atlas/generator/sharding/testSlippyTile
Labels: New Feature
