Repository osmlab/atlas-generator, pull requests merged in 2019-11, with the labels that each got.

#123 RDD keys now use JSON instead of ad-hoc strings
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
  src/main/java/org/openstreetmap/atlas/generator/persistence/AbstractMultipleAtlasBasedOutputFormat.java
  src/main/java/org/openstreetmap/atlas/generator/persistence/MultipleAtlasCountryStatisticsOutputFormat.java
  src/main/java/org/openstreetmap/atlas/generator/tools/json/PersistenceJsonParser.java
  src/test/java/org/openstreetmap/atlas/generator/tools/json/PersistenceJsonParserTest.java
Labels: Breaking Change, New Feature

#126 Output Format for FeatureChange lists
  src/integrationTest/java/org/openstreetmap/atlas/generator/AtlasGeneratorIntegrationTest.java
  src/integrationTest/java/org/openstreetmap/atlas/generator/persistence/FeatureChangeOutputFormatIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/generator/persistence/FeatureChangeOutputFormat.java
  src/main/java/org/openstreetmap/atlas/generator/persistence/MultipleFeatureChangeOutputFormat.java
  src/main/java/org/openstreetmap/atlas/generator/tools/streaming/ResourceFileSystem.java
Labels: New Feature

#127 AbstractFileOutputFormat: Retry when closing the stream
  src/main/java/org/openstreetmap/atlas/generator/persistence/AbstractFileOutputFormat.java
Labels: Enhancement
