Repository osmlab/atlas-generator, pull requests merged in 2019-02, with the labels that each got.

#75 Use latest atlas 5.3.4
  dependencies.gradle
Labels: Enhancement

#76 PbfLocator: Protect against file system failures
  src/main/java/org/openstreetmap/atlas/generator/PbfLocator.java
  src/main/java/org/openstreetmap/atlas/generator/creator/RawAtlasCreator.java
Labels: Bug, Enhancement

#79 Save Atlas as line delimited geojson
  src/integrationTest/java/org/openstreetmap/atlas/generator/AtlasGeneratorIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorParameters.java
  src/main/java/org/openstreetmap/atlas/generator/persistence/AbstractMultipleAtlasBasedOutputFormat.java
  src/main/java/org/openstreetmap/atlas/generator/persistence/LineDelimitedGeojsonOutputFormat.java
  src/main/java/org/openstreetmap/atlas/generator/persistence/MultipleLineDelimitedGeojsonOutputFormat.java
Labels: New Feature

#80 Travis: Ensure right commit is tagged
  .travis/tag-master.sh
Labels: Bug

#78 Dynamic slicing
  dependencies.gradle
  src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
  src/main/java/org/openstreetmap/atlas/generator/creator/RawAtlasCreator.java
Labels: New Feature

#81 Integration Test for dynamic relation slicing
  src/integrationTest/java/org/openstreetmap/atlas/generator/slicing/DynamicRelationSlicingIntegrationTest.java
  src/integrationTest/resources/org/openstreetmap/atlas/generator/slicing/ABC_1-0-0.txt
  src/integrationTest/resources/org/openstreetmap/atlas/generator/slicing/ABC_1-0-1.txt
  src/integrationTest/resources/org/openstreetmap/atlas/generator/slicing/ABC_1-1-0.txt
  src/integrationTest/resources/org/openstreetmap/atlas/generator/slicing/ABC_1-1-1.txt
  src/integrationTest/resources/org/openstreetmap/atlas/generator/slicing/DEF_1-0-1.txt
  src/integrationTest/resources/org/openstreetmap/atlas/generator/slicing/DEF_1-1-1.txt
  src/integrationTest/resources/org/openstreetmap/atlas/generator/slicing/simpleBoundaryFile.txt
  src/integrationTest/resources/org/openstreetmap/atlas/generator/slicing/simpleSharding.txt
  src/integrationTest/resources/org/openstreetmap/atlas/generator/slicing/waterbody.josm.osm
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
Labels: Enhancement
