Repository osmlab/atlas-generator, pull requests merged in 2019-07, with the labels that each got.

#105 Use ArrangementCheck
  .circleci/config.yml
  README.md
  build.gradle
  config/checkstyle/arrangement.txt
  config/checkstyle/checkstyle.xml
  dependencies.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/org/openstreetmap/atlas/generator/AtlasGenerationTask.java
  src/main/java/org/openstreetmap/atlas/generator/tools/spark/rdd/ShardedAtlasRDDLoader.java
Labels: New Feature

#106 Proper centralization of resource accession
  src/integrationTest/java/org/openstreetmap/atlas/generator/AtlasGeneratorIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/generator/sharding/AtlasSharding.java
  src/main/java/org/openstreetmap/atlas/generator/tools/spark/converters/ConfigurationConverter.java
  src/main/java/org/openstreetmap/atlas/generator/tools/spark/persistence/PersistenceTools.java
Labels: Bug

#108 Added configured filter output option to Atlas Generation
  src/integrationTest/java/org/openstreetmap/atlas/generator/AtlasGeneratorIntegrationTest.java
  src/integrationTest/resources/org/openstreetmap/atlas/generator/nothingFilter.json
  src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorHelper.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorJobGroup.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorParameters.java
  src/main/java/org/openstreetmap/atlas/generator/world/AtlasFilePathFilter.java
  src/main/java/org/openstreetmap/atlas/generator/world/WorldMultiAtlasGenerator.java
Labels: Enhancement, New Feature

#109 Depend on Atlas 5.7.3
  dependencies.gradle
Labels: Duplicate
