Repository osmlab/atlas-generator, pull requests merged in 2020-03, with the labels that each got.

#140 Prevent NPE in AtlasSharding when resource does not exist
  src/main/java/org/openstreetmap/atlas/generator/sharding/AtlasSharding.java
  src/test/java/org/openstreetmap/atlas/generator/sharding/AtlasShardingTest.java
Labels: Bug

#141 Use latest Atlas 6.1.2
  dependencies.gradle
Labels: Bug, Enhancement

#142 Make AtlasStatistics optional
  src/integrationTest/java/org/openstreetmap/atlas/generator/AtlasGeneratorIntegrationTest.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGenerator.java
  src/main/java/org/openstreetmap/atlas/generator/AtlasGeneratorParameters.java
Labels: Enhancement

#143 HadoopAtlasFileCache tests now performed sequentially
  src/test/java/org/openstreetmap/atlas/generator/tools/caching/HadoopAtlasFileCacheTest.java
Labels: Bug
